# Generated by Django 4.1.1 on 2022-11-10 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HeadeRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=50)),
                ("record_indicator", models.IntegerField()),
                ("nem_version", models.CharField(max_length=10)),
                ("date_time", models.DateTimeField()),
                ("from_participant", models.CharField(max_length=10)),
                ("to_participant", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="AccumlationRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nmi", models.CharField(max_length=10)),
                ("meter_serial_number", models.CharField(max_length=12)),
                (
                    "meter_reading_value",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                ("reading_date", models.DateTimeField()),
                (
                    "header_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nem_records.headerecord",
                    ),
                ),
            ],
        ),
    ]
