# Generated by Django 4.1.1 on 2022-11-10 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nem_records", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AccumlationRecord",
            new_name="AccumulationRecord",
        ),
        migrations.RenameModel(
            old_name="HeadeRecord",
            new_name="HeaderRecord",
        ),
    ]
